### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by boldt** [florian/react-shortcut-chooser#2]
The Demo linked in the README doesn't work anymore.

**Comment by florian** [comment]
It works for me. What browser are you using?
Did you read the node "It sometimes takes RequireBin a while to load the NPM modules though"? You need to wait a little bit for it to load everything from NPM.

**Comment by boldt** [comment]
What means "a while"/"a bit"? I'm waiting for half an hour now and nothing happens. 

* Chrome Version 59.0.3071.115 (64-Bit), Ubuntu 14.04.05

**Comment by marco-a** [comment]
The demo works for me on OS X 10.12.5 (Chrome 59.0.3071.115) and Ubuntu 14.04 LTS (Firefox 54).

**Comment by florian** [comment]
@marco-a Thanks a lot for the testing!

@boldt Does the input field show up? Are you focusing on the input when pressing a keyboard shortcut? What keys exactly did you try pressing? The demo is configured to require at least one modifier key (Cmd, Alt, Shift)

**Comment by boldt** [comment]
It works now...
